### ISSUE TITLE
2.26日已失效

### ISSUE THREAD

**Issue by Zxis233** [james-curtis/abbyy-fine-reader-crack#1]

**Comment by james-curtis** [comment]
可以前往出处找最新版
出处
简中论坛 https://forum.freemdict.com/t/topic/23171/6
原破，需要注册登录 https://nsaneforums.com/topic/442672-abbyy-finereader-pdf-16-v160147295/#comment-1794960

**Comment by Zxis233** [comment]
谢谢您！16可以使用，但是没有PDF打印机的功能。
